import { BaseLayout } from '@ngagio/layouts/base-layout';
import { QueryProvider } from '@ngagio/providers/query-provider';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>
          <BaseLayout>{children}</BaseLayout>
        </QueryProvider>
      </body>
    </html>
  );
}
